const translations = {
  ko: {
    loadingText: {text: "데이터 불러오는 중..."},
    loginTitle: {text: "로그인 또는 게스트 플레이"},
    modalGoogleLoginBtn: {text: "Google 계정으로 로그인"},
    loginInfo: {html: "또는 닉네임을 입력하여 게스트로 플레이하세요.<br>닉네임은 랭킹에 표시되며 변경할 수 없습니다."},
    loginInfoGoogle: {html: "이전에 사용하던 닉네임이 있는 경우 해당 닉네임을 입력하여 계속 플레이할 수 있습니다.<br>닉네임은 랭킹에 표시되며 변경할 수 없습니다."},
    usernameInput: {placeholder: "닉네임 입력"},
    usernameSubmit: {text: "게스트로 시작하기"},
    mergeTitle: {text: "진행 상황 병합"},
    mergeMessage: {text: "현재 로컬 진행 상황을 Google 계정과 병합하시겠습니까?"},
    mergeConfirmBtn: {text: "네"},
    mergeCancelBtn: {text: "제 계정이 아닙니다"},
    overallRankingTitle: {text: "🏆 전체 랭킹"},
    overallRankingList: {text: "로딩 중…"},
      startBtn: {text: "시작하기"},
      tutorialBtn: {text: "튜토리얼"},
      manageModulesBtn: {text: "모듈 관리"},
      copyStatusBtn: {text: "공유하기"},
      googleLoginBtn: {text: "Google 로그인"},
      languageBtn: {text: "한영전환"},
    guestbookTitle: {text: "📝 개발자(이현준)한테 글 남기기"},
    guestNicknameLabel: {html: "닉네임: <b id='guestUsername'></b>"},
    guestMessage: {placeholder: "남기고 싶은 말..."},
    guestSubmitBtn: {text: "등록"},
    coffeeBtn: {text: "☕ 개발자(이현준)한테 커피 사주기"},
    shareTitle: {text: "🔗 공유할 내용"},
    copyShareBtn: {text: "복사하기"},
    closeShareBtn: {text: "닫기"},
    backToMainFromManagement: {text: "← 메인으로"},
    moduleManagementTitle: {text: "📦 모듈 관리"},
    createModuleBtn: {text: "+ 새 모듈 만들기"},
    moduleTitle: {text: "🛠 모듈 제작 모드"},
    moduleWireStatusInfo: {text: "Ctrl - 도선 그리기"},
    moduleWireDeleteInfo: {text: "Shift - 도선/블록 삭제"},
    moduleDeleteAllInfo: {text: "R - 회로 초기화"},
    saveModuleBtn: {text: "모듈 저장하기"},
    moduleInfoTitle: {text: "모듈 정보 입력"},
    moduleNameInput: {placeholder: "모듈 이름 (영문/숫자, 최대 8자)", title:"영문자(A–Z, a–z)와 숫자(0–9)만 사용 가능합니다."},
    moduleDescInput: {placeholder: "모듈 설명 (선택)"},
    confirmSaveModuleBtn: {text: "저장하기"},
    cancelSaveModuleBtn: {text: "취소"},
    "exit-module-mode": {text: "← 돌아가기"},
    backToMainFromProblem: {text: "← 메인으로"},
    problemCreatorTitle: {text: "📝 문제 출제"},
    inputLabel: {text: "입력"},
    outputLabel: {text: "출력"},
    rowLabel: {text: "행"},
    colLabel: {text: "열"},
    updateIOBtn: {text: "적용"},
    addTestcaseRowBtn: {text: "+ 행 추가"},
    computeOutputsBtn: {text: "출력 계산"},
    problemWireStatusInfo: {text: "Ctrl - 도선 그리기"},
    problemWireDeleteInfo: {text: "Shift - 도선/블록 삭제"},
    problemDeleteAllInfo: {text: "R - 회로 초기화"},
    saveProblemBtn: {text: "문제 저장"},
    problemInfoTitle: {text: "문제 정보 입력"},
    problemTitleInput: {placeholder: "문제 제목"},
    problemDescInput: {placeholder: "문제 설명"},
    confirmSaveProblemBtn: {text: "저장하기"},
    cancelSaveProblemBtn: {text: "취소"},
    chapterTitle: {text: "📚 스테이지 선택"},
    backToMainFromChapter: {text: "← 메인으로"},
    backToMainBtn: {text: "← 메인으로"},
    backToChapterFromUserProblems: {text: "← 챕터로"},
    userProblemsTitle: {text: "📝 사용자 문제"},
    openProblemCreatorBtn: {text: "문제 만들기"},
    rankingTitle: {text: "🏆 랭킹"},
    hintTitle: {text: "💡 힌트"},
    hintLabel: {text: "힌트"},
    hintReady: {text: "다음 힌트를 바로 볼 수 있습니다."},
    hintCountdown: {text: "다음 힌트까지 {time}"},
    noHints: {text: "힌트가 없습니다."},
    startStageFirst: {text: "먼저 스테이지를 시작하세요."},
    adHintBtn: {text: "광고 보고 힌트 얻기"},
    closeHintBtn: {text: "닫기"},
    closeHintMessageBtn: {text: "닫기"},
    gradeButton: {text: "채점하기"},
    wireStatusInfo: {text: "Ctrl - 도선 그리기"},
    wireDeleteInfo: {text: "Shift - 도선/블록 삭제"},
    DeleteAllInfo: {text: "R - 회로 초기화"},
    returnToEditBtn: {text: "🛠 편집으로 돌아가기"},
    prevStageBtnMenu: {text: "← 이전 스테이지"},
    saveCircuitBtn: {text: "💾 회로 저장"},
    viewSavedBtn: {text: "💾 저장된 회로 보기"},
    viewRankingBtn: {text: "🏆 랭킹 보기"},
    showIntroBtn: {text: "ℹ️ 스테이지 안내"},
    hintBtn: {text: "💡 힌트"},
    backToLevelsBtn: {text: "← 레벨 선택으로"},
    nextStageBtnMenu: {text: "다음 스테이지 →"},
    tutPrevBtn: {text: "이전"},
    tutNextBtn: {text: "다음"},
    tutFinishBtn: {text: "튜토리얼 마치기"},
    tutCloseBtn: {text: "닫기"},
    savedListTitle: {text: "💾 저장된 회로 목록"},
    closeSavedModal: {text: "닫기"},
    gifLoadingText: {text: "GIF 생성중..."},
    savingCircuit: {text: "회로 저장 중..."},
    circuitSaved: {text: "회로가 저장되었습니다!"},
    savedShareBtn: {text: "공유하기"},
    savedNextBtn: {text: "계속"},
    problemListTitle: {text: "📂 저장된 문제"},
    closeProblemListModal: {text: "닫기"},
    clearedTitle: {html: "스테이지 <span id='clearedStageNumber'></span> 클리어!"},
    prevStageBtn: {text: "이전 스테이지"},
    nextStageBtn: {text: "다음 스테이지"},
    startLevelBtn: {text: "시작하기"},
    stageTutBtn: {text: "시작하기"},
    loadBtn: {text: "불러오기"},
    deleteBtn: {text: "삭제"},
    logoutBtn: {text: "로그아웃"},
    outputMissingAlert: {text: "❌ 다음 출력 블록이 배치되지 않았습니다: {list}"},
    loginFailed: {text: "로그인에 실패했습니다. 코드: {code}, 메시지: {message}"},
    noModules: {text: "저장된 모듈이 없습니다."},
    noCircuits: {text: "저장된 회로가 없습니다."},
    noProblems: {text: "저장된 문제가 없습니다."},
    noUserProblems: {text: "등록된 문제가 없습니다."},
    confirmDeleteModule: {text: "정말 '{module}' 모듈을 삭제하시겠습니까?"},
    confirmDelete: {text: "정말 삭제하시겠습니까?"},
    loadFailedNoData: {text: "불러오기 실패: 데이터가 없습니다"},
    moduleLoadFailed: {text: "⚠️ 모듈 불러오기 실패: 데이터가 없습니다"},
    loadFailed: {text: "불러오기 실패"},
    deleteFailed: {text: "삭제 실패: {error}"},
    confirmDeleteAll: {text: "⚠️ 모든 블록과 배선을 삭제하시겠습니까?"},
    computeOutputsFirst: {text: "출력 계산을 먼저 실행하세요."},
    problemSaved: {text: "문제가 저장되었습니다."},
    saveFailed: {text: "저장 실패: {error}"},
    thInput: {text: "입력"},
    thExpected: {text: "예상 출력"},
    thActual: {text: "실제 출력"},
    thResult: {text: "결과"},
    thRank: {text: "순위"},
    thNickname: {text: "닉네임"},
    thStage: {text: "스테이지"},
    thBlocks: {text: "블럭"},
    thWires: {text: "도선"},
    thHintUsed: {text: "힌트 사용"},
    thTime: {text: "시간"},
    thTitle: {text: "제목"},
    thGrid: {text: "그리드"},
    thNotes: {text: "비고"},
    thCreator: {text: "제작자"},
    thCreatedAt: {text: "제작일"},
    thSolved: {text: "해결 수"},
    thLikes: {text: "좋아요"}
  },
  en: {
    loadingText: {text: "Loading data..."},
    loginTitle: {text: "Login or play as guest"},
    modalGoogleLoginBtn: {text: "Sign in with Google"},
    loginInfo: {html: "Or enter a nickname to play as a guest.<br>The nickname appears in the ranking and cannot be changed."},
    loginInfoGoogle: {html: "If you previously used a nickname, enter it to continue playing.<br>The nickname appears in the ranking and cannot be changed."},
    usernameInput: {placeholder: "Enter nickname"},
    usernameSubmit: {text: "Start as guest"},
    mergeTitle: {text: "Merge Progress"},
    mergeMessage: {text: "Merge local progress with your Google account?"},
    mergeConfirmBtn: {text: "Yes"},
    mergeCancelBtn: {text: "Not my account"},
    overallRankingTitle: {text: "🏆 Global Ranking"},
    overallRankingList: {text: "Loading..."},
    startBtn: {text: "Start"},
    tutorialBtn: {text: "Tutorial"},
    manageModulesBtn: {text: "Manage Modules"},
    copyStatusBtn: {text: "Share"},
    googleLoginBtn: {text: "Google Login"},
    languageBtn: {text: "Change Language"},
    guestbookTitle: {text: "📝 Leave a message for the developer (Hyeonjun Lee)"},
    guestNicknameLabel: {html: "Nickname: <b id='guestUsername'></b>"},
    guestMessage: {placeholder: "Message..."},
    guestSubmitBtn: {text: "Submit"},
    coffeeBtn: {text: "☕ Buy the developer (Hyeonjun Lee) a coffee"},
    shareTitle: {text: "🔗 Shareable content"},
    copyShareBtn: {text: "Copy"},
    closeShareBtn: {text: "Close"},
    backToMainFromManagement: {text: "← Back to Main"},
    moduleManagementTitle: {text: "📦 Module Management"},
    createModuleBtn: {text: "+ Create Module"},
    moduleTitle: {text: "🛠 Module Builder Mode"},
    moduleWireStatusInfo: {text: "Ctrl - Draw wire"},
    moduleWireDeleteInfo: {text: "Shift - Delete wire/block"},
    moduleDeleteAllInfo: {text: "R - Reset circuit"},
    saveModuleBtn: {text: "Save Module"},
    moduleInfoTitle: {text: "Enter Module Info"},
    moduleNameInput: {placeholder: "Module name (alphanumeric, max 8)", title:"Only A–Z, a–z, 0–9 allowed."},
    moduleDescInput: {placeholder: "Module description (optional)"},
    confirmSaveModuleBtn: {text: "Save"},
    cancelSaveModuleBtn: {text: "Cancel"},
    "exit-module-mode": {text: "← Back"},
    backToMainFromProblem: {text: "← Back to Main"},
    problemCreatorTitle: {text: "📝 Problem Creator"},
    inputLabel: {text: "Inputs"},
    outputLabel: {text: "Outputs"},
    rowLabel: {text: "Rows"},
    colLabel: {text: "Cols"},
    updateIOBtn: {text: "Apply"},
    addTestcaseRowBtn: {text: "+ Add row"},
    computeOutputsBtn: {text: "Compute outputs"},
    problemWireStatusInfo: {text: "Ctrl - Draw wire"},
    problemWireDeleteInfo: {text: "Shift - Delete wire/block"},
    problemDeleteAllInfo: {text: "R - Reset circuit"},
    saveProblemBtn: {text: "Save Problem"},
    problemInfoTitle: {text: "Enter Problem Info"},
    problemTitleInput: {placeholder: "Problem title"},
    problemDescInput: {placeholder: "Problem description"},
    confirmSaveProblemBtn: {text: "Save"},
    cancelSaveProblemBtn: {text: "Cancel"},
    chapterTitle: {text: "📚 Select Stage"},
    backToMainFromChapter: {text: "← Back to Main"},
    backToMainBtn: {text: "← Back to Main"},
    backToChapterFromUserProblems: {text: "← Back to Chapters"},
    userProblemsTitle: {text: "📝 User Problems"},
    openProblemCreatorBtn: {text: "Create Problem"},
    rankingTitle: {text: "🏆 Ranking"},
    hintTitle: {text: "💡 Hint"},
    hintLabel: {text: "Hint"},
    hintReady: {text: "You can view the next hint now."},
    hintCountdown: {text: "Time until next hint {time}"},
    noHints: {text: "No hints available."},
    startStageFirst: {text: "Start a stage first."},
    adHintBtn: {text: "Watch ad to get hint"},
    closeHintBtn: {text: "Close"},
    closeHintMessageBtn: {text: "Close"},
    gradeButton: {text: "Grade"},
    wireStatusInfo: {text: "Ctrl - Draw wire"},
    wireDeleteInfo: {text: "Shift - Delete wire/block"},
    DeleteAllInfo: {text: "R - Reset circuit"},
    returnToEditBtn: {text: "🛠 Back to Edit"},
    prevStageBtnMenu: {text: "← Previous Stage"},
    saveCircuitBtn: {text: "💾 Save Circuit"},
    viewSavedBtn: {text: "💾 View Saved Circuits"},
    viewRankingBtn: {text: "🏆 View Ranking"},
    showIntroBtn: {text: "ℹ️ Stage Info"},
    hintBtn: {text: "💡 Hint"},
    backToLevelsBtn: {text: "← Back to Level Select"},
    nextStageBtnMenu: {text: "Next Stage →"},
    tutPrevBtn: {text: "Prev"},
    tutNextBtn: {text: "Next"},
    tutFinishBtn: {text: "Finish Tutorial"},
    tutCloseBtn: {text: "Close"},
    savedListTitle: {text: "💾 Saved Circuits"},
    closeSavedModal: {text: "Close"},
    gifLoadingText: {text: "Generating GIF..."},
    savingCircuit: {text: "Saving circuit..."},
    circuitSaved: {text: "Circuit saved!"},
    savedShareBtn: {text: "Share"},
    savedNextBtn: {text: "Next"},
    problemListTitle: {text: "📂 Saved Problems"},
    closeProblemListModal: {text: "Close"},
    clearedTitle: {html: "Stage <span id='clearedStageNumber'></span> Cleared!"},
    prevStageBtn: {text: "Previous Stage"},
    nextStageBtn: {text: "Next Stage"},
    startLevelBtn: {text: "Start"},
    stageTutBtn: {text: "Start"},
    loadBtn: {text: "Load"},
    deleteBtn: {text: "Delete"},
    logoutBtn: {text: "Logout"},
    outputMissingAlert: {text: "❌ Missing output blocks: {list}"},
    loginFailed: {text: "Login failed. Code: {code}, Message: {message}"},
    noModules: {text: "No saved modules."},
    noCircuits: {text: "No saved circuits."},
    noProblems: {text: "No saved problems."},
    noUserProblems: {text: "No problems available."},
    confirmDeleteModule: {text: "Are you sure you want to delete module '{module}'?"},
    confirmDelete: {text: "Are you sure you want to delete?"},
    loadFailedNoData: {text: "Load failed: No data"},
    moduleLoadFailed: {text: "⚠️ Failed to load module: No data"},
    loadFailed: {text: "Load failed"},
    deleteFailed: {text: "Delete failed: {error}"},
    confirmDeleteAll: {text: "⚠️ Delete all blocks and wires?"},
    computeOutputsFirst: {text: "Please compute outputs first."},
    problemSaved: {text: "Problem saved."},
    saveFailed: {text: "Save failed: {error}"},
    thInput: {text: "Input"},
    thExpected: {text: "Expected"},
    thActual: {text: "Actual"},
    thResult: {text: "Result"},
    thRank: {text: "Rank"},
    thNickname: {text: "Nickname"},
    thStage: {text: "Stage"},
    thBlocks: {text: "Blocks"},
    thWires: {text: "Wires"},
    thHintUsed: {text: "Hints"},
    thTime: {text: "Time"},
    thTitle: {text: "Title"},
    thGrid: {text: "Grid"},
    thNotes: {text: "Notes"},
    thCreator: {text: "Creator"},
    thCreatedAt: {text: "Created"},
    thSolved: {text: "Solved"},
    thLikes: {text: "Likes"}
  }
};

let currentLang = localStorage.getItem('lang') || (navigator.language && navigator.language.startsWith('ko') ? 'ko' : 'en');

function applyTranslations() {
  const langMap = translations[currentLang];
  Object.keys(langMap).forEach(id => {
    const el = document.getElementById(id);
    if (!el) return;
    const {text, html, placeholder, title} = langMap[id];
    if (text !== undefined) el.textContent = text;
    if (html !== undefined) el.innerHTML = html;
    if (placeholder !== undefined) el.setAttribute('placeholder', placeholder);
    if (title !== undefined) el.setAttribute('title', title);
  });
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('lang', lang);
  location.reload();
}

document.addEventListener('DOMContentLoaded', () => {
  applyTranslations();
  const langBtn = document.getElementById('languageBtn');
  if (langBtn) {
    langBtn.addEventListener('click', () => {
      setLanguage(currentLang === 'ko' ? 'en' : 'ko');
    });
  }
});

window.currentLang = currentLang;
window.t = function(id) {
  const entry = translations[currentLang][id] || translations['en'][id];
  return entry && (entry.text || entry.html) || id;
};
window.setLanguage = setLanguage;
