const translations = {
  ko: {
    loadingText: {text: "데이터 불러오는 중..."},
    mergeTitle: {text: "진행 상황 병합"},
    mergeMessage: {text: "현재 로컬 진행 상황을 Google 계정과 병합하시겠습니까?"},
    mergeConfirmBtn: {text: "네"},
    mergeCancelBtn: {text: "제 계정이 아닙니다"},
    overallRankingTitle: {text: "🏆 전체 랭킹"},
    overallRankingList: {text: "로딩 중…"},
    labBtn: {title: "실험실", ariaLabel: "실험실"},
    chapterNavBtn: {title: "스테이지 선택", ariaLabel: "스테이지 선택"},
    userProblemsBtn: {title: "사용자 문제", ariaLabel: "사용자 문제"},
    userProblemsLocked: {text: "사용자 문제는 챕터 1~6을 모두 클리어하면 열립니다."},
      startBtn: {text: "시작하기"},
      tutorialBtn: {text: "튜토리얼"},
      copyStatusBtn: {text: "공유하기"},
      googleLoginBtn: {text: "Google 로그인"},
      settingsBtn: {text: "⚙️ 설정"},
      languageBtn: {text: "English"},
      loginGuestPrompt: {text: "구글 로그인을 통해 여러 기기에서 Bitwiser를 즐겨보세요!"},
      loginRankOverallLabel: {text: "전체 순위"},
      loginRankClearedLabel: {text: "클리어한 스테이지 수"},
    guestbookTitle: {text: "📝 개발자(이현준)한테 글 남기기"},
    guestNicknameLabel: {html: "닉네임: <b id='guestUsername'></b>"},
    guestMessage: {placeholder: "남기고 싶은 말..."},
    guestSubmitBtn: {text: "등록"},
    coffeeBtn: {text: "☕ 개발자(이현준)한테 커피 사주기"},
    shareTitle: {text: "🔗 공유할 내용"},
    copyShareBtn: {text: "복사하기"},
    closeShareBtn: {text: "닫기"},
    settingsTitle: {text: "🛠️설정"},
    autoSaveLabel: {text: "회로 자동 저장"},
    settingsCloseBtn: {text: "닫기"},
    backToMainFromProblem: {text: "← 메인으로"},
    problemCreatorTitle: {text: "📝 문제 출제"},
    addRowTopBtn: {text: "+ 행", title: "위쪽 행 추가", ariaLabel: "위쪽 행 추가"},
    removeRowTopBtn: {text: "- 행", title: "위쪽 행 제거", ariaLabel: "위쪽 행 제거"},
    addRowBottomBtn: {text: "+ 행", title: "아래쪽 행 추가", ariaLabel: "아래쪽 행 추가"},
    removeRowBottomBtn: {text: "- 행", title: "아래쪽 행 제거", ariaLabel: "아래쪽 행 제거"},
    addColLeftBtn: {text: "+ 열", title: "왼쪽 열 추가", ariaLabel: "왼쪽 열 추가"},
    removeColLeftBtn: {text: "- 열", title: "왼쪽 열 제거", ariaLabel: "왼쪽 열 제거"},
    addColRightBtn: {text: "+ 열", title: "오른쪽 열 추가", ariaLabel: "오른쪽 열 추가"},
    removeColRightBtn: {text: "- 열", title: "오른쪽 열 제거", ariaLabel: "오른쪽 열 제거"},
    inputLabel: {text: "입력"},
    outputLabel: {text: "출력"},
    rowLabel: {text: "행"},
    colLabel: {text: "열"},
    updateIOBtn: {text: "적용"},
    addTestcaseRowBtn: {text: "+ 행 추가"},
    computeOutputsBtn: {text: "출력 계산"},
    problemWireMoveInfo: {title: "기본 상태", ariaLabel: "기본 상태"},
    problemWireStatusInfo: {title: "Ctrl / Cmd - 도선 그리기", ariaLabel: "Ctrl / Cmd - 도선 그리기"},
    problemWireDeleteInfo: {title: "Shift - 도선/블록 삭제", ariaLabel: "Shift - 도선/블록 삭제"},
    problemWireSelectInfo: {title: "마우스 오른쪽 - 선택", ariaLabel: "마우스 오른쪽 - 선택"},
    problemDeleteAllInfo: {title: "R - 회로 초기화", ariaLabel: "R - 회로 초기화"},
    saveProblemBtn: {text: "문제 저장"},
    problemInfoTitle: {text: "문제 정보 입력"},
    problemTitleInput: {placeholder: "문제 제목"},
    problemDescInput: {placeholder: "문제 설명"},
    problemDifficultyLabel: {text: "난이도"},
    problemDifficultyValue: {text: "{value}/5"},
    problemDifficultyStarAria: {text: "난이도 {value}점"},
    problemGridSizeLabel: {text: "격자 크기"},
    fixIOCheckLabel: {text: "IN/OUT 위치 고정"},
    confirmSaveProblemBtn: {text: "저장하기"},
    cancelSaveProblemBtn: {text: "취소"},
    chapterTitle: {text: "📚 스테이지 선택"},
    backToMainFromChapter: {text: "← 메인으로"},
    backToMainBtn: {text: "← 메인으로"},
    backToChapterFromUserProblems: {text: "← 메인으로"},
    userProblemsTitle: {text: "📝 사용자 문제"},
    openProblemCreatorBtn: {text: "문제 만들기"},
    userProblemSearchLabel: {text: "검색"},
    userProblemSearch: {placeholder: "제목 또는 from:제작자"},
    userProblemSortLabel: {text: "정렬"},
    userProblemSortLatestOption: {text: "최신순"},
    userProblemSortPopularOption: {text: "인기순"},
    userProblemSortSolvedOption: {text: "해결순"},
    userProblemSortDifficultyOption: {text: "난이도순"},
    userProblemSortNameOption: {text: "이름순"},
    userProblemSearchHelp: {text: "예: XOR, from:garden"},
    userProblemFilterMine: {text: "나의 문제"},
    userProblemFilterUnsolved: {text: "미해결"},
    userProblemFilterPopular: {text: "인기"},
    userProblemAdvancedSummary: {text: "⚙ 필터"},
    userProblemFilterGridLabel: {text: "그리드 크기"},
    userProblemFilterGridAnyOption: {text: "전체"},
    userProblemFilterDifficultyLabel: {text: "난이도"},
    userProblemFilterDifficultyAll: {text: "전체"},
    userProblemFilterDifficultyEasy: {text: "쉬움"},
    userProblemFilterDifficultyNormal: {text: "보통"},
    userProblemFilterDifficultyHard: {text: "어려움"},
    userProblemFilterMinLikesLabel: {text: "좋아요 수 이상"},
    userProblemMinLikes: {placeholder: "0"},
    userProblemFilterCreatorLabel: {text: "제작자"},
    userProblemCreatorFilter: {placeholder: "예: garden"},
    userProblemResetFilters: {text: "필터 초기화"},
    userProblemResultSummaryTemplate: {text: "총 {total}개 중 {visible}개 표시"},
    userProblemNoMatch: {text: "조건에 맞는 문제가 없습니다."},
    userProblemLoadFailed: {text: "문제 목록을 불러오지 못했습니다."},
    rankingTitle: {text: "🏆 랭킹"},
    hintTitle: {text: "💡 힌트"},
    hintLabel: {text: "힌트"},
    hintReady: {text: "다음 힌트를 바로 볼 수 있습니다."},
    hintCountdown: {text: "다음 힌트까지 {time}"},
    noHints: {text: "힌트가 없습니다."},
    startStageFirst: {text: "먼저 스테이지를 시작하세요."},
    adHintBtn: {text: "광고 보고 힌트 얻기"},
    closeHintBtn: {text: "닫기"},
    closeHintMessageBtn: {text: "닫기"},
    gradeButton: {text: "채점하기"},
    wireMoveInfo: {title: "기본 상태", ariaLabel: "기본 상태"},
    wireStatusInfo: {title: "Ctrl / Cmd - 도선 그리기", ariaLabel: "Ctrl / Cmd - 도선 그리기"},
    wireDeleteInfo: {title: "Shift - 도선/블록 삭제", ariaLabel: "Shift - 도선/블록 삭제"},
    wireSelectInfo: {title: "마우스 오른쪽 - 선택", ariaLabel: "마우스 오른쪽 - 선택"},
    DeleteAllInfo: {title: "R - 회로 초기화", ariaLabel: "R - 회로 초기화"},
    usedBlocksLabel: {text: "블록 수"},
    usedWiresLabel: {text: "도선 수"},
    problemUsedBlocksLabel: {text: "블록 수"},
    problemUsedWiresLabel: {text: "도선 수"},
    returnToEditBtn: {text: "🛠 편집으로 돌아가기"},
    prevStageBtnMenu: {text: "← 이전 스테이지"},
    saveCircuitBtn: {text: "💾 회로 저장"},
    viewSavedBtn: {text: "💾 저장된 회로 보기"},
    viewRankingBtn: {text: "🏆 랭킹 보기"},
    showIntroBtn: {text: "ℹ️ 스테이지 안내"},
    hintBtn: {text: "💡 힌트"},
    backToLevelsBtn: {text: "← 레벨 선택으로"},
    nextStageBtnMenu: {text: "다음 스테이지 →"},
    tutPrevBtn: {text: "이전"},
    tutNextBtn: {text: "다음"},
    tutFinishBtn: {text: "튜토리얼 마치기"},
    tutCloseBtn: {text: "닫기"},
    savedListTitle: {text: "💾 저장된 회로 목록"},
    closeSavedModal: {text: "닫기"},
    gifLoadingText: {text: "GIF 생성중..."},
    saveGifBtn: {text: "이미지 저장"},
    copyGifBtn: {text: "이미지 복사"},
    shareGifBtn: {text: "공유하기"},
    closeGifModal: {text: "닫기"},
    savingCircuit: {text: "회로 저장 중..."},
    circuitSaved: {text: "회로가 저장되었습니다!"},
    loginToSaveCircuit: {text: "회로를 저장하려면 구글 로그인을 해주세요."},
    savedShareBtn: {text: "공유하기"},
    savedNextBtn: {text: "계속"},
    problemListTitle: {text: "📂 저장된 문제"},
    closeProblemListModal: {text: "닫기"},
    clearedTitle: {html: "스테이지 <span id='clearedStageNumber'></span> 클리어!"},
    prevStageBtn: {text: "이전 스테이지"},
    nextStageBtn: {text: "다음 스테이지"},
    startLevelBtn: {text: "시작하기"},
    stageTutBtn: {text: "시작하기"},
    loadBtn: {text: "불러오기"},
    deleteBtn: {text: "삭제"},
    logoutBtn: {text: "로그아웃"},
    outputMissingAlert: {text: "❌ 다음 출력 블록이 배치되지 않았습니다: {list}"},
    noOutputsDefined: {text: "출력 블록을 먼저 배치해주세요."},
    loginFailed: {text: "로그인에 실패했습니다. 코드: {code}, 메시지: {message}"},
    noCircuits: {text: "저장된 회로가 없습니다."},
    noProblems: {text: "저장된 문제가 없습니다."},
    noUserProblems: {text: "등록된 문제가 없습니다."},
    confirmDelete: {text: "정말 삭제하시겠습니까?"},
    loadFailedNoData: {text: "불러오기 실패: 데이터가 없습니다"},
    incompatibleCircuit: {text: "이 회로도는 이전 버전과 호환되지 않습니다."},
    loadFailed: {text: "불러오기 실패"},
    loginRequired: {text: "로그인이 필요합니다."},
    googleLoginPrompt: {text: "구글 로그인을 해주세요."},
    deleteFailed: {text: "삭제 실패: {error}"},
    confirmDeleteAll: {text: "⚠️ 모든 블록과 배선을 삭제하시겠습니까?"},
    computeOutputsFirst: {text: "출력 계산을 먼저 실행하세요."},
    problemTitleRequired: {text: "문제 제목을 입력해주세요."},
    problemDescRequired: {text: "문제 설명을 입력해주세요."},
    problemSaved: {text: "문제가 저장되었습니다."},
    saveFailed: {text: "저장 실패: {error}"},
    thInput: {text: "입력"},
    thExpected: {text: "예상 출력"},
    thActual: {text: "실제 출력"},
    thResult: {text: "결과"},
    thRank: {text: "순위"},
    thNickname: {text: "닉네임"},
    thStage: {text: "스테이지"},
    thBlocks: {text: "블럭"},
    thWires: {text: "도선"},
    thHintUsed: {text: "힌트 사용"},
    thTime: {text: "시간"},
    thTitle: {text: "제목"},
    thGrid: {text: "그리드"},
    thNotes: {text: "비고"},
    thCreator: {text: "제작자"},
    thCreatedAt: {text: "제작일"},
    thSolved: {text: "해결 수"},
    thLikes: {text: "좋아요"}
  },
  en: {
    loadingText: {text: "Loading data..."},
    mergeTitle: {text: "Merge Progress"},
    mergeMessage: {text: "Merge local progress with your Google account?"},
    mergeConfirmBtn: {text: "Yes"},
    mergeCancelBtn: {text: "Not my account"},
    overallRankingTitle: {text: "🏆 Global Ranking"},
    overallRankingList: {text: "Loading..."},
    labBtn: {title: "Lab", ariaLabel: "Lab"},
    chapterNavBtn: {title: "Select Stages", ariaLabel: "Select Stages"},
    userProblemsBtn: {title: "User Problems", ariaLabel: "User Problems"},
    userProblemsLocked: {text: "User problems unlock after clearing stages 1-6."},
    startBtn: {text: "Start"},
    tutorialBtn: {text: "Tutorial"},
    copyStatusBtn: {text: "Share"},
    googleLoginBtn: {text: "Google Login"},
    settingsBtn: {text: "⚙️ Settings"},
    languageBtn: {text: "한국어"},
    loginGuestPrompt: {text: "Log in with Google to enjoy Bitwiser across devices!"},
    loginRankOverallLabel: {text: "Global Rank"},
    loginRankClearedLabel: {text: "Stages Cleared"},
    guestbookTitle: {text: "📝 Leave a message for the developer (Hyeonjun Lee)"},
    guestNicknameLabel: {html: "Nickname: <b id='guestUsername'></b>"},
    guestMessage: {placeholder: "Message..."},
    guestSubmitBtn: {text: "Submit"},
    coffeeBtn: {text: "☕ Buy the developer (Hyeonjun Lee) a coffee"},
    shareTitle: {text: "🔗 Shareable content"},
    copyShareBtn: {text: "Copy"},
    closeShareBtn: {text: "Close"},
    settingsTitle: {text: "🛠️ Settings"},
    autoSaveLabel: {text: "Auto-save circuit"},
    settingsCloseBtn: {text: "Close"},
    backToMainFromProblem: {text: "← Back to Main"},
    problemCreatorTitle: {text: "📝 Problem Creator"},
    addRowTopBtn: {text: "+ Row", title: "Add top row", ariaLabel: "Add top row"},
    removeRowTopBtn: {text: "- Row", title: "Remove top row", ariaLabel: "Remove top row"},
    addRowBottomBtn: {text: "+ Row", title: "Add bottom row", ariaLabel: "Add bottom row"},
    removeRowBottomBtn: {text: "- Row", title: "Remove bottom row", ariaLabel: "Remove bottom row"},
    addColLeftBtn: {text: "+ Col", title: "Add left column", ariaLabel: "Add left column"},
    removeColLeftBtn: {text: "- Col", title: "Remove left column", ariaLabel: "Remove left column"},
    addColRightBtn: {text: "+ Col", title: "Add right column", ariaLabel: "Add right column"},
    removeColRightBtn: {text: "- Col", title: "Remove right column", ariaLabel: "Remove right column"},
    inputLabel: {text: "Inputs"},
    outputLabel: {text: "Outputs"},
    rowLabel: {text: "Rows"},
    colLabel: {text: "Cols"},
    updateIOBtn: {text: "Apply"},
    addTestcaseRowBtn: {text: "+ Add row"},
    computeOutputsBtn: {text: "Compute outputs"},
    problemWireMoveInfo: {title: "Default mode", ariaLabel: "Default mode"},
    problemWireStatusInfo: {title: "Ctrl / Cmd - Draw wire", ariaLabel: "Ctrl or Cmd - Draw wire"},
    problemWireDeleteInfo: {title: "Shift - Delete wire/block", ariaLabel: "Shift - Delete wire or block"},
    problemWireSelectInfo: {title: "Right click - Select", ariaLabel: "Right click - Select"},
    problemDeleteAllInfo: {title: "R - Reset circuit", ariaLabel: "R - Reset circuit"},
    saveProblemBtn: {text: "Save Problem"},
    problemInfoTitle: {text: "Enter Problem Info"},
    problemTitleInput: {placeholder: "Problem title"},
    problemDescInput: {placeholder: "Problem description"},
    problemDifficultyLabel: {text: "Difficulty"},
    problemDifficultyValue: {text: "{value}/5"},
    problemDifficultyStarAria: {text: "Difficulty {value} out of 5"},
    problemGridSizeLabel: {text: "Grid size"},
    fixIOCheckLabel: {text: "Fix IN/OUT positions"},
    confirmSaveProblemBtn: {text: "Save"},
    cancelSaveProblemBtn: {text: "Cancel"},
    chapterTitle: {text: "📚 Select Stage"},
    backToMainFromChapter: {text: "← Back to Main"},
    backToMainBtn: {text: "← Back to Main"},
    backToChapterFromUserProblems: {text: "← Back to Main"},
    userProblemsTitle: {text: "📝 User Problems"},
    openProblemCreatorBtn: {text: "Create Problem"},
    userProblemSearchLabel: {text: "Search"},
    userProblemSearch: {placeholder: "Title or from:creator"},
    userProblemSortLabel: {text: "Sort"},
    userProblemSortLatestOption: {text: "Latest"},
    userProblemSortPopularOption: {text: "Popular"},
    userProblemSortSolvedOption: {text: "Most solved"},
    userProblemSortDifficultyOption: {text: "Difficulty"},
    userProblemSortNameOption: {text: "Name"},
    userProblemSearchHelp: {text: "e.g. XOR, from:garden"},
    userProblemFilterMine: {text: "My Problems"},
    userProblemFilterUnsolved: {text: "Unsolved"},
    userProblemFilterPopular: {text: "Popular"},
    userProblemAdvancedSummary: {text: "⚙ Filters"},
    userProblemFilterGridLabel: {text: "Grid size"},
    userProblemFilterGridAnyOption: {text: "All"},
    userProblemFilterDifficultyLabel: {text: "Difficulty"},
    userProblemFilterDifficultyAll: {text: "All"},
    userProblemFilterDifficultyEasy: {text: "Easy"},
    userProblemFilterDifficultyNormal: {text: "Normal"},
    userProblemFilterDifficultyHard: {text: "Hard"},
    userProblemFilterMinLikesLabel: {text: "Likes at least"},
    userProblemMinLikes: {placeholder: "0"},
    userProblemFilterCreatorLabel: {text: "Creator"},
    userProblemCreatorFilter: {placeholder: "e.g. garden"},
    userProblemResetFilters: {text: "Reset filters"},
    userProblemResultSummaryTemplate: {text: "Showing {visible} of {total} problems"},
    userProblemNoMatch: {text: "No problems match the selected filters."},
    userProblemLoadFailed: {text: "Failed to load user problems."},
    rankingTitle: {text: "🏆 Ranking"},
    hintTitle: {text: "💡 Hint"},
    hintLabel: {text: "Hint"},
    hintReady: {text: "You can view the next hint now."},
    hintCountdown: {text: "Time until next hint {time}"},
    noHints: {text: "No hints available."},
    startStageFirst: {text: "Start a stage first."},
    adHintBtn: {text: "Watch ad to get hint"},
    closeHintBtn: {text: "Close"},
    closeHintMessageBtn: {text: "Close"},
    gradeButton: {text: "Grade"},
    wireMoveInfo: {title: "Default mode", ariaLabel: "Default mode"},
    wireStatusInfo: {title: "Ctrl / Cmd - Draw wire", ariaLabel: "Ctrl or Cmd - Draw wire"},
    wireDeleteInfo: {title: "Shift - Delete wire/block", ariaLabel: "Shift - Delete wire or block"},
    wireSelectInfo: {title: "Right click - Select", ariaLabel: "Right click - Select"},
    DeleteAllInfo: {title: "R - Reset circuit", ariaLabel: "R - Reset circuit"},
    usedBlocksLabel: {text: "Blocks"},
    usedWiresLabel: {text: "Wires"},
    problemUsedBlocksLabel: {text: "Blocks"},
    problemUsedWiresLabel: {text: "Wires"},
    returnToEditBtn: {text: "🛠 Back to Edit"},
    prevStageBtnMenu: {text: "← Previous Stage"},
    saveCircuitBtn: {text: "💾 Save Circuit"},
    viewSavedBtn: {text: "💾 View Saved Circuits"},
    viewRankingBtn: {text: "🏆 View Ranking"},
    showIntroBtn: {text: "ℹ️ Stage Info"},
    hintBtn: {text: "💡 Hint"},
    backToLevelsBtn: {text: "← Back to Level Select"},
    nextStageBtnMenu: {text: "Next Stage →"},
    tutPrevBtn: {text: "Prev"},
    tutNextBtn: {text: "Next"},
    tutFinishBtn: {text: "Finish Tutorial"},
    tutCloseBtn: {text: "Close"},
    savedListTitle: {text: "💾 Saved Circuits"},
    closeSavedModal: {text: "Close"},
    gifLoadingText: {text: "Generating GIF..."},
    saveGifBtn: {text: "Save Image"},
    copyGifBtn: {text: "Copy Image"},
    shareGifBtn: {text: "Share"},
    closeGifModal: {text: "Close"},
    savingCircuit: {text: "Saving circuit..."},
    circuitSaved: {text: "Circuit saved!"},
    loginToSaveCircuit: {text: "Log in with Google to save the circuit."},
    savedShareBtn: {text: "Share"},
    savedNextBtn: {text: "Next"},
    problemListTitle: {text: "📂 Saved Problems"},
    closeProblemListModal: {text: "Close"},
    clearedTitle: {html: "Stage <span id='clearedStageNumber'></span> Cleared!"},
    prevStageBtn: {text: "Previous Stage"},
    nextStageBtn: {text: "Next Stage"},
    startLevelBtn: {text: "Start"},
    stageTutBtn: {text: "Start"},
    loadBtn: {text: "Load"},
    deleteBtn: {text: "Delete"},
    logoutBtn: {text: "Logout"},
    outputMissingAlert: {text: "❌ Missing output blocks: {list}"},
    noOutputsDefined: {text: "Place at least one output block first."},
    loginFailed: {text: "Login failed. Code: {code}, Message: {message}"},
    noCircuits: {text: "No saved circuits."},
    noProblems: {text: "No saved problems."},
    noUserProblems: {text: "No problems available."},
    confirmDelete: {text: "Are you sure you want to delete?"},
    loadFailedNoData: {text: "Load failed: No data"},
    incompatibleCircuit: {text: "This circuit is incompatible with the current version."},
    loadFailed: {text: "Load failed"},
    loginRequired: {text: "Login required."},
    googleLoginPrompt: {text: "Please log in with Google."},
    deleteFailed: {text: "Delete failed: {error}"},
    confirmDeleteAll: {text: "⚠️ Delete all blocks and wires?"},
    computeOutputsFirst: {text: "Please compute outputs first."},
    problemTitleRequired: {text: "Please enter a problem title."},
    problemDescRequired: {text: "Please enter a problem description."},
    problemSaved: {text: "Problem saved."},
    saveFailed: {text: "Save failed: {error}"},
    thInput: {text: "Input"},
    thExpected: {text: "Expected"},
    thActual: {text: "Actual"},
    thResult: {text: "Result"},
    thRank: {text: "Rank"},
    thNickname: {text: "Nickname"},
    thStage: {text: "Stage"},
    thBlocks: {text: "Blocks"},
    thWires: {text: "Wires"},
    thHintUsed: {text: "Hints"},
    thTime: {text: "Time"},
    thTitle: {text: "Title"},
    thGrid: {text: "Grid"},
    thNotes: {text: "Notes"},
    thCreator: {text: "Creator"},
    thCreatedAt: {text: "Created"},
    thSolved: {text: "Solved"},
    thLikes: {text: "Likes"}
  }
};

let currentLang = localStorage.getItem('lang') || (navigator.language && navigator.language.startsWith('ko') ? 'ko' : 'en');

function applyTranslations() {
  const langMap = translations[currentLang];
  Object.keys(langMap).forEach(id => {
    const el = document.getElementById(id);
    if (!el) return;
    const {text, html, placeholder, title, ariaLabel} = langMap[id];
    if (text !== undefined) el.textContent = text;
    if (html !== undefined) el.innerHTML = html;
    if (placeholder !== undefined) el.setAttribute('placeholder', placeholder);
    if (title !== undefined) el.setAttribute('title', title);
    if (ariaLabel !== undefined) el.setAttribute('aria-label', ariaLabel);
  });
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('lang', lang);
  location.reload();
}

document.addEventListener('DOMContentLoaded', () => {
  applyTranslations();
  const langBtn = document.getElementById('languageBtn');
  if (langBtn) {
    langBtn.addEventListener('click', () => {
      setLanguage(currentLang === 'ko' ? 'en' : 'ko');
    });
  }
});

window.currentLang = currentLang;
window.t = function(id) {
  const entry = translations[currentLang][id] || translations['en'][id];
  return entry && (entry.text || entry.html) || id;
};
window.setLanguage = setLanguage;
