const translations = {
  ko: {
    loadingText: {text: "데이터 불러오는 중..."},
    loginTitle: {text: "로그인 또는 게스트 플레이"},
    modalGoogleLoginBtn: {text: "Google 계정으로 로그인"},
    loginInfo: {html: "또는 닉네임을 입력하여 게스트로 플레이하세요.<br>닉네임은 랭킹에 표시되며 변경할 수 없습니다."},
    loginInfoGoogle: {html: "이전에 사용하던 닉네임이 있는 경우 해당 닉네임을 입력하여 계속 플레이할 수 있습니다.<br>닉네임은 랭킹에 표시되며 변경할 수 없습니다."},
    usernameInput: {placeholder: "닉네임 입력"},
    usernameSubmit: {text: "게스트로 시작하기"},
    mergeTitle: {text: "진행 상황 병합"},
    mergeMessage: {text: "현재 로컬 진행 상황을 Google 계정과 병합하시겠습니까?"},
    mergeConfirmBtn: {text: "네"},
    mergeCancelBtn: {text: "제 계정이 아닙니다"},
    overallRankingTitle: {text: "🏆 전체 랭킹"},
    overallRankingList: {text: "로딩 중…"},
    labBtn: {title: "실험실", ariaLabel: "실험실"},
    userProblemsBtn: {title: "사용자 문제", ariaLabel: "사용자 문제"},
    userProblemsLocked: {text: "사용자 문제는 챕터 1~6을 모두 클리어하면 열립니다."},
      startBtn: {text: "시작하기"},
      tutorialBtn: {text: "튜토리얼"},
      copyStatusBtn: {text: "공유하기"},
      googleLoginBtn: {text: "Google 로그인"},
      settingsBtn: {text: "⚙️"},
      languageBtn: {text: "English"},
    loginGuestPrompt: {text: "구글 로그인을 통해 여러 기기에서 Bitwiser를 즐겨보세요!"},
    loginRankOverallLabel: {text: "전체 순위"},
    loginRankClearedLabel: {text: "클리어한 스테이지 수"},
    loginPanelTitle: {text: "프로필 & 로그인"},
    rankingPanelTitle: {text: "🏆 전체 랭킹"},
    guestbookPanelTitle: {text: "📝 방명록"},
    stageDetailTitle: {text: "스테이지를 선택하세요"},
    stageDetailDescription: {text: "맵에서 노드를 선택하면 상세 정보를 볼 수 있습니다."},
    stageUntitled: {text: "이름 없는 스테이지"},
    stageDetailLockedMessage: {text: "이 스테이지는 아직 잠겨 있습니다."},
    stageDetailClearedMessage: {text: "이미 클리어한 스테이지입니다."},
    stageDetailReadyMessage: {text: "플레이할 준비가 되었습니다!"},
    stageDetailPlayBtn: {text: "시작하기"},
    stageTypePrimitive: {text: "기초 게이트"},
    stageTypeLogic: {text: "논리 회로"},
    stageTypeArithmetic: {text: "연산 회로"},
    stageTypeMode: {text: "모드 바로가기"},
    stageTypeTitle: {text: "칭호"},
    stageDetailShortcutReady: {text: "바로가기를 눌러 이동하세요."},
    stageDetailShortcutCleared: {text: "바로가기를 이용했습니다."},
    stageDetailOpenBtn: {text: "열기"},
    stageDetailComingSoonStatus: {text: "새 스테이지를 준비 중입니다."},
    stageDetailComingSoonDescription: {text: "곧 플레이할 수 있도록 준비하고 있어요."},
    stageDetailComingSoonBtn: {text: "준비 중"},
    stageDetailTitleBtn: {text: "획득 조건"},
    stageDetailTitleUnlocked: {text: "칭호를 획득했습니다!"},
    stageDetailTitleLocked: {text: "모든 조건을 달성하면 칭호를 받을 수 있어요."},
    stageDetailTitleDescription: {text: "이전 스테이지를 모두 완료하면 자동으로 지급되는 칭호입니다."},
    stageDetailLabDescription: {text: "실험실 모드로 이동해 자유롭게 회로를 실험해보세요."},
    stageDetailUserDescription: {text: "사용자 제작 문제 목록으로 이동합니다."},
    stageDetailModeDescription: {text: "특별 모드 화면으로 이동하는 바로가기 노드입니다."},
    guestbookTitle: {text: "📝 개발자(이현준)한테 글 남기기"},
    guestNicknameLabel: {html: "닉네임: <b id='guestUsername'></b>"},
    guestMessage: {placeholder: "남기고 싶은 말..."},
    guestSubmitBtn: {text: "등록"},
    coffeeBtn: {text: "☕ 개발자(이현준)한테 커피 사주기"},
    shareTitle: {text: "🔗 공유할 내용"},
    copyShareBtn: {text: "복사하기"},
    closeShareBtn: {text: "닫기"},
    settingsTitle: {text: "🛠️설정"},
    themeHeading: {text: "🎨 테마"},
    themePreviewLabel: {text: "미리보기"},
    autoSaveLabel: {text: "회로 자동 저장"},
    bgmLabel: {text: "BGM"},
    sfxLabel: {text: "SFX"},
    settingsCloseBtn: {text: "닫기"},
    backToMainFromProblem: {text: "← 메인으로"},
    problemCreatorTitle: {text: "📝 문제 출제"},
    gridSizeControllerLabel: {text: "🧭 격자 크기"},
    addRowTopBtn: {text: "↑", title: "위쪽 행 추가", ariaLabel: "위쪽 행 추가"},
    removeRowTopBtn: {text: "↓", title: "위쪽 행 제거", ariaLabel: "위쪽 행 제거"},
    addRowBottomBtn: {text: "↓", title: "아래쪽 행 추가", ariaLabel: "아래쪽 행 추가"},
    removeRowBottomBtn: {text: "↑", title: "아래쪽 행 제거", ariaLabel: "아래쪽 행 제거"},
    addColLeftBtn: {text: "←", title: "왼쪽 열 추가", ariaLabel: "왼쪽 열 추가"},
    removeColLeftBtn: {text: "→", title: "왼쪽 열 제거", ariaLabel: "왼쪽 열 제거"},
    addColRightBtn: {text: "→", title: "오른쪽 열 추가", ariaLabel: "오른쪽 열 추가"},
    removeColRightBtn: {text: "←", title: "오른쪽 열 제거", ariaLabel: "오른쪽 열 제거"},
    inputLabel: {text: "입력"},
    outputLabel: {text: "출력"},
    rowLabel: {text: "행"},
    colLabel: {text: "열"},
    problemWireMoveInfo: {title: "기본 상태", ariaLabel: "기본 상태"},
    problemWireStatusInfo: {title: "Ctrl / Cmd - 도선 그리기", ariaLabel: "Ctrl / Cmd - 도선 그리기"},
    problemWireDeleteInfo: {title: "Shift - 도선/블록 삭제", ariaLabel: "Shift - 도선/블록 삭제"},
    problemWireSelectInfo: {title: "마우스 오른쪽 - 선택", ariaLabel: "마우스 오른쪽 - 선택"},
    problemDeleteAllInfo: {title: "R - 회로 초기화", ariaLabel: "R - 회로 초기화"},
    saveProblemBtn: {text: "문제 저장"},
    problemInfoTitle: {text: "문제 정보 입력"},
    problemTitleInput: {placeholder: "문제 제목"},
    problemDescInput: {placeholder: "문제 설명"},
    problemDifficultyLabel: {text: "난이도"},
    problemDifficultyValue: {text: "{value}/5"},
    problemDifficultyStarAria: {text: "난이도 {value}점"},
    problemGridSizeLabel: {text: "격자 크기"},
    fixIOCheckLabel: {text: "IN/OUT 위치 고정"},
    confirmSaveProblemBtn: {text: "저장하기"},
    cancelSaveProblemBtn: {text: "취소"},
    problemSaveNeedsIO: {text: "IN과 OUT 블록을 각각 최소 1개 이상 배치하세요."},
    problemSaveNeedsSequentialIO: {text: "IN, OUT 블록 번호를 1부터 순서대로 설정하세요."},
    problemSaveFixErrors: {text: "회로 오류를 먼저 해결해주세요."},
    backToMainBtn: {text: "← 메인으로"},
    backToStageMapFromUserProblems: {text: "← 스테이지 맵으로"},
    userProblemsTitle: {text: "📝 사용자 문제"},
    openProblemCreatorBtn: {text: "문제 만들기"},
    userProblemSearchLabel: {text: "검색"},
    userProblemSearch: {placeholder: "제목 또는 from:제작자"},
    userProblemSortLabel: {text: "정렬"},
    userProblemSortLatestOption: {text: "최신순"},
    userProblemSortPopularOption: {text: "인기순"},
    userProblemSortSolvedOption: {text: "해결순"},
    userProblemSortDifficultyOption: {text: "난이도순"},
    userProblemSortNameOption: {text: "이름순"},
    userProblemSearchHelp: {text: "예: XOR, from:garden"},
    userProblemFilterMine: {text: "나의 문제"},
    userProblemFilterUnsolved: {text: "미해결"},
    userProblemFilterPopular: {text: "인기"},
    userProblemAdvancedSummary: {text: "⚙ 필터"},
    userProblemFilterGridLabel: {text: "그리드 크기"},
    userProblemFilterGridAnyOption: {text: "전체"},
    userProblemFilterDifficultyLabel: {text: "난이도"},
    userProblemFilterDifficultyAll: {text: "전체"},
    userProblemFilterDifficultyEasy: {text: "쉬움"},
    userProblemFilterDifficultyNormal: {text: "보통"},
    userProblemFilterDifficultyHard: {text: "어려움"},
    userProblemFilterMinLikesLabel: {text: "좋아요 수 이상"},
    userProblemMinLikes: {placeholder: "0"},
    userProblemFilterCreatorLabel: {text: "제작자"},
    userProblemCreatorFilter: {placeholder: "예: garden"},
    userProblemResetFilters: {text: "필터 초기화"},
    userProblemResultSummaryTemplate: {text: "총 {total}개 중 {visible}개 표시"},
    userProblemNoMatch: {text: "조건에 맞는 문제가 없습니다."},
    problemUntitled: {text: "제목 없는 문제"},
    userProblemLoadFailed: {text: "문제 목록을 불러오지 못했습니다."},
    rankingTitle: {text: "🏆 랭킹"},
    hintTitle: {text: "💡 힌트"},
    hintLabel: {text: "힌트"},
    hintReady: {text: "다음 힌트를 바로 볼 수 있습니다."},
    hintCountdown: {text: "다음 힌트까지 {time}"},
    noHints: {text: "힌트가 없습니다."},
    startStageFirst: {text: "먼저 스테이지를 시작하세요."},
    adHintBtn: {text: "광고 보고 힌트 얻기"},
    closeHintBtn: {text: "닫기"},
    closeHintMessageBtn: {text: "닫기"},
    gradeButton: {text: "채점하기"},
    wireMoveInfo: {title: "기본 상태", ariaLabel: "기본 상태"},
    wireStatusInfo: {title: "Ctrl / Cmd - 도선 그리기", ariaLabel: "Ctrl / Cmd - 도선 그리기"},
    wireDeleteInfo: {title: "Shift - 도선/블록 삭제", ariaLabel: "Shift - 도선/블록 삭제"},
    wireSelectInfo: {title: "마우스 오른쪽 - 선택", ariaLabel: "마우스 오른쪽 - 선택"},
    DeleteAllInfo: {title: "R - 회로 초기화", ariaLabel: "R - 회로 초기화"},
    usedBlocksLabel: {text: "블록 수"},
    usedWiresLabel: {text: "도선 수"},
    problemUsedBlocksLabel: {text: "블록 수"},
    problemUsedWiresLabel: {text: "도선 수"},
    returnToEditBtn: {text: "🛠 편집으로 돌아가기"},
    saveCircuitBtn: {text: "💾 회로 저장"},
    viewSavedBtn: {text: "💾 저장된 회로 보기"},
    viewRankingBtn: {text: "🏆 랭킹 보기"},
    showIntroBtn: {text: "ℹ️ 스테이지 안내"},
    hintBtn: {text: "💡 힌트"},
    backToLevelsBtn: {text: "← 레벨 선택으로"},
    tutPrevBtn: {text: "이전"},
    tutNextBtn: {text: "다음"},
    tutFinishBtn: {text: "튜토리얼 마치기"},
    tutCloseBtn: {text: "닫기"},
    savedListTitle: {text: "💾 저장된 회로 목록"},
    closeSavedModal: {text: "닫기"},
    gifLoadingText: {text: "GIF 생성중..."},
    saveGifBtn: {text: "이미지 저장"},
    copyGifBtn: {text: "이미지 복사"},
    shareGifBtn: {text: "공유하기"},
    closeGifModal: {text: "닫기"},
    savingCircuit: {text: "회로 저장 중..."},
    circuitSaved: {text: "회로가 저장되었습니다!"},
    loginToSaveCircuit: {text: "회로를 저장하려면 구글 로그인을 해주세요."},
    savedShareBtn: {text: "공유하기"},
    savedNextBtn: {text: "계속"},
    problemListTitle: {text: "📂 저장된 문제"},
    closeProblemListModal: {text: "닫기"},
    clearedTitle: {html: "<span id='clearedStageName'></span> 클리어!"},
    startLevelBtn: {text: "시작하기"},
    clearedNextBtn: {text: "다음"},
    loadBtn: {text: "불러오기"},
    deleteBtn: {text: "삭제"},
    logoutBtn: {text: "로그아웃"},
    outputMissingAlert: {text: "❌ 다음 출력 블록이 배치되지 않았습니다: {list}"},
    loginFailed: {text: "로그인에 실패했습니다. 코드: {code}, 메시지: {message}"},
    noCircuits: {text: "저장된 회로가 없습니다."},
    noProblems: {text: "저장된 문제가 없습니다."},
    noUserProblems: {text: "등록된 문제가 없습니다."},
    confirmDelete: {text: "정말 삭제하시겠습니까?"},
    loadFailedNoData: {text: "불러오기 실패: 데이터가 없습니다"},
    incompatibleCircuit: {text: "이 회로도는 이전 버전과 호환되지 않습니다."},
    loadFailed: {text: "불러오기 실패"},
    loginRequired: {text: "로그인이 필요합니다."},
    googleLoginPrompt: {text: "구글 로그인을 해주세요."},
    deleteFailed: {text: "삭제 실패: {error}"},
    confirmDeleteAll: {text: "⚠️ 모든 블록과 배선을 삭제하시겠습니까?"},
    problemTitleRequired: {text: "문제 제목을 입력해주세요."},
    problemDescRequired: {text: "문제 설명을 입력해주세요."},
    problemSaved: {text: "문제가 저장되었습니다."},
    saveFailed: {text: "저장 실패: {error}"},
    thInput: {text: "입력"},
    thExpected: {text: "예상 출력"},
    thActual: {text: "실제 출력"},
    thResult: {text: "결과"},
    thRank: {text: "순위"},
    thNickname: {text: "닉네임"},
    thStage: {text: "스테이지"},
    thBlocks: {text: "블럭"},
    thWires: {text: "도선"},
    thHintUsed: {text: "힌트 사용"},
    thTime: {text: "시간"},
    thTitle: {text: "제목"},
    thGrid: {text: "그리드"},
    thNotes: {text: "비고"},
    thCreator: {text: "제작자"},
    thCreatedAt: {text: "제작일"},
    thSolved: {text: "해결 수"},
    thLikes: {text: "좋아요"},
    orientationWarningText: {text: "⚠️ Bitwiser는 가로 모드를 권장합니다."},
    orientationTipText: {text: "Tip: [홈 화면에 추가 → 설치]를 통해 Bitwiser 앱을 설치할 수 있어요!"},
    closeOrientationBtn: {text: "닫기"},
    mainTagline: {text: "Play bitwise. Become bit wiser."},
    mobileNavRankingText: {text: "랭킹"},
    mobileNavRankingIcon: {alt: "랭킹"},
    mobileNavHomeText: {text: "메인"},
    mobileNavHomeIcon: {alt: "메인"},
    mobileNavGuestbookText: {text: "방명록"},
    mobileNavGuestbookIcon: {alt: "방명록"},
    labExitBtn: {text: "⟲ 메인으로", ariaLabel: "메인으로 돌아가기"},
    communityShareClose: {ariaLabel: "닫기"},
    communityShareTitleLabel: {text: "회로 커뮤니티에 올리기"},
    communityShareIntro: {text: "현재 실험실 회로를 커뮤니티에 공유합니다."},
    communityShareTitleFieldLabel: {text: "회로 제목"},
    communityShareTitle: {placeholder: "예: 4비트 패리티 생성기"},
    communityShareDescriptionLabel: {text: "설명 (선택)"},
    communityShareDescription: {placeholder: "회로 동작 방식이나 사용 팁을 간단히 남겨주세요."},
    communityShareCancel: {text: "취소"},
    communityShareSubmit: {text: "공유하기"},
    communityBrowserTitle: {text: "회로 커뮤니티"},
    communityBrowserClose: {ariaLabel: "닫기"},
    communityLoading: {text: "회로 목록을 불러오는 중..."},
    communityEmptyState: {text: "아직 등록된 회로가 없습니다."},
    labCommunityTitle: {text: "🌐 회로 커뮤니티"},
    labShareCommunityBtn: {text: "회로 커뮤니티에 올리기"},
    labOpenCommunityBtn: {text: "회로 커뮤니티 보기"},
    labCommunityLoginHint: {text: "Google 로그인 후 이용할 수 있습니다."},
    userProblemsSubtitle: {text: "커뮤니티가 만든 회로 퍼즐을 검색하고 정렬해보세요."},
    userProblemFallbackTitle: {text: "사용자 문제"},
    circuitError: {text: "회로에 오류가 존재합니다"},
    featureComingSoon: {text: "준비중인 기능입니다."},
    communityUnknownUser: {text: "알 수 없는 사용자"},
    anonymousUser: {text: "익명"},
    communityLoginRequired: {text: "Google 로그인 후 이용해주세요."},
    communityFirestoreUnavailable: {text: "Firestore 연결을 확인해주세요."},
    communityStatsUnavailable: {text: "회로 정보를 불러올 수 없습니다."},
    communityStatsTemplate: {text: "블록 {blocks}개 · 도선 {wires}개"},
    communityFirestoreInitFailed: {text: "Firestore 초기화에 실패했습니다."},
    communityCircuitNotFound: {text: "회로를 찾을 수 없어요."},
    communityUploadInProgress: {text: "회로를 업로드하는 중입니다..."},
    communityUntitledCircuit: {text: "제목 없는 회로"},
    communityShareSuccess: {text: "커뮤니티에 회로를 공유했습니다!"},
    communityShareSuccessStatus: {text: "회로가 커뮤니티에 업로드되었습니다."},
    communityUploadFailed: {text: "업로드에 실패했습니다. 잠시 후 다시 시도해주세요."},
    communityCardMetaTemplate: {text: "{author} • {date}"},
    communityCardStatsTemplate: {text: "블록 {blocks}개 · 도선 {wires}개"},
    communityLoadButton: {text: "이 회로 불러오기"},
    communityLoadCircuitFailed: {text: "회로 데이터를 불러오지 못했습니다."},
    communityApplyCircuitFailed: {text: "회로를 불러오는 데 실패했습니다."},
    communityLoadCircuitSuccess: {text: "커뮤니티 회로를 불러왔습니다."},
    communityDeleteButton: {text: "내 회로 삭제"},
    communityDeleteConfirm: {text: "정말로 이 회로를 삭제할까요? 되돌릴 수 없습니다."},
    communityDeleting: {text: "삭제 중..."},
    communityDeleteSuccess: {text: "회로를 삭제했습니다."},
    communityDeleteSuccessStatus: {text: "커뮤니티 회로를 삭제했습니다."},
    communityDeleteSuccessEmpty: {text: "회로를 삭제했습니다. 현재 등록된 회로가 없습니다."},
    communityDeleteFailed: {text: "회로 삭제에 실패했습니다. 잠시 후 다시 시도해주세요."},
    communityListLoading: {text: "회로 목록을 불러오는 중입니다..."},
    communityListEmpty: {text: "아직 등록된 회로가 없어요. 첫 번째로 공유해보세요!"},
    communityListLoaded: {text: "총 {count}개의 회로를 불러왔습니다."},
    communityListLoadFailed: {text: "회로 목록을 가져오지 못했습니다."},
    communityStatusLoginRequired: {text: "Google 로그인 후 이용해주세요."},
    guestbookMessageRequired: {text: "내용을 입력해주세요!"},
    guestbookSubmitFailed: {text: "전송에 실패했습니다."},
    circuitErrorAlert: {text: "회로에 오류가 존재합니다"},
    gifCopySuccess: {text: "이미지가 클립보드에 복사되었습니다."},
    gifCopyFailed: {text: "이미지 복사에 실패했습니다."},
    gifShareNotSupported: {text: "이 브라우저에서는 공유하기를 지원하지 않습니다."},
    saveCircuitError: {text: "회로 저장 중 오류가 발생했습니다."},
    statusShareIntro: {text: "Bitwiser를 플레이했습니다!"},
    statusShareCopySuccess: {text: "클립보드에 복사되었습니다!"},
    statusShareCopyFailed: {text: "복사에 실패했습니다: {error}"},
    statusShareNoSavedCircuit: {text: "최근 저장된 회로가 없습니다."},
    statusShareNoGif: {text: "공유할 GIF가 없습니다."},
    statusShareNotSupported: {text: "공유를 지원하지 않는 브라우저입니다."},
    statusShareFailed: {text: "공유에 실패했습니다: {error}"},
    gradingMultipleInputs: {text: "❌ {blockType} 블록에 여러 입력이 연결되어 있습니다. 회로를 수정해주세요."},
    gradingResultsHeading: {html: "<b>채점 결과:</b><br><br>"},
    gradingCorrect: {text: "✅ 정답"},
    gradingIncorrect: {text: "❌ 오답"},
    gradingAllPassed: {text: "🎉 모든 테스트를 통과했습니다!"},
    gradingSomeFailed: {text: "😢 일부 테스트에 실패했습니다."},
    rankingLoading: {text: "로딩 중…"},
    noRanking: {text: "랭킹이 없습니다."},
    refreshRankingBtn: {text: "🔄 새로고침"},
    closeRankingBtn: {text: "닫기"},
    rankingLoadFailed: {text: "랭킹을 불러오지 못했습니다."},
    rankingSelectLevelFirst: {text: "먼저 레벨을 선택해주세요."},
    loginNicknameRequired: {text: "닉네임을 입력해주세요."},
    loginNicknameTaken: {text: "이미 사용 중인 닉네임입니다."},
    loginNicknameRegisterError: {text: "닉네임 등록 중 오류가 발생했습니다."},
    loginRegisterButton: {text: "닉네임 등록"},
    loginModalTitleGoogle: {text: "Google 닉네임 등록"},
    loginNicknameExists: {text: "이미 있는 닉네임입니다."},
    loginMergePromptTitle: {html: "<p><b>{targetName}</b> 닉네임의 진행 상황</p>"},
    loginMergePromptSummary: {html: "<li>클리어 레벨 수: {cleared}</li><li>사용 블록 수: {blocks}</li><li>사용 도선 : {wires}</li>"},
    loginMergePromptQuestion: {text: "이 계정과 진행 상황을 합치겠습니까?"},
    loginConfirm: {text: "네"},
    loginCancel: {text: "제 계정이 아닙니다"},
    authUnknownError: {text: "알 수 없는 오류가 발생했습니다."},
    usernameRegistering: {text: "닉네임 등록"},
    rankOverall: {text: "전체"}
  },
  en: {
    loadingText: {text: "Loading data..."},
    loginTitle: {text: "Login or play as guest"},
    modalGoogleLoginBtn: {text: "Sign in with Google"},
    loginInfo: {html: "Or enter a nickname to play as a guest.<br>The nickname appears in the ranking and cannot be changed."},
    loginInfoGoogle: {html: "If you previously used a nickname, enter it to continue playing.<br>The nickname appears in the ranking and cannot be changed."},
    usernameInput: {placeholder: "Enter nickname"},
    usernameSubmit: {text: "Start as guest"},
    mergeTitle: {text: "Merge Progress"},
    mergeMessage: {text: "Merge local progress with your Google account?"},
    mergeConfirmBtn: {text: "Yes"},
    mergeCancelBtn: {text: "Not my account"},
    overallRankingTitle: {text: "🏆 Global Ranking"},
    overallRankingList: {text: "Loading..."},
    labBtn: {title: "Lab", ariaLabel: "Lab"},
    userProblemsBtn: {title: "User Problems", ariaLabel: "User Problems"},
    userProblemsLocked: {text: "User problems unlock after clearing stages 1-6."},
    startBtn: {text: "Start"},
    tutorialBtn: {text: "Tutorial"},
    copyStatusBtn: {text: "Share"},
    googleLoginBtn: {text: "Google Login"},
    settingsBtn: {text: "⚙️"},
    languageBtn: {text: "한국어"},
    loginGuestPrompt: {text: "Log in with Google to enjoy Bitwiser across devices!"},
    loginRankOverallLabel: {text: "Global Rank"},
    loginRankClearedLabel: {text: "Stages Cleared"},
    loginPanelTitle: {text: "Profile & Login"},
    rankingPanelTitle: {text: "🏆 Global Ranking"},
    guestbookPanelTitle: {text: "📝 Guestbook"},
    stageDetailTitle: {text: "Select a stage"},
    stageDetailDescription: {text: "Tap a node on the map to view its details."},
    stageUntitled: {text: "Untitled stage"},
    stageDetailLockedMessage: {text: "This stage is still locked."},
    stageDetailClearedMessage: {text: "You already cleared this stage."},
    stageDetailReadyMessage: {text: "Ready to play!"},
    stageDetailPlayBtn: {text: "Play"},
    stageTypePrimitive: {text: "Primitive Gate"},
    stageTypeLogic: {text: "Logic Circuit"},
    stageTypeArithmetic: {text: "Arithmetic"},
    stageTypeMode: {text: "Mode Shortcut"},
    stageTypeTitle: {text: "Title"},
    stageDetailShortcutReady: {text: "Use the shortcut to jump there."},
    stageDetailShortcutCleared: {text: "Shortcut visited."},
    stageDetailOpenBtn: {text: "Open"},
    stageDetailComingSoonStatus: {text: "New stage coming soon."},
    stageDetailComingSoonDescription: {text: "We are preparing this stage for a future update."},
    stageDetailComingSoonBtn: {text: "Coming soon"},
    stageDetailTitleBtn: {text: "Requirements"},
    stageDetailTitleUnlocked: {text: "Title unlocked!"},
    stageDetailTitleLocked: {text: "Clear every prerequisite to earn this title."},
    stageDetailTitleDescription: {text: "Titles are automatically awarded after clearing every linked stage."},
    stageDetailLabDescription: {text: "Head to Lab Mode and experiment freely."},
    stageDetailUserDescription: {text: "Browse the list of user-created problems."},
    stageDetailModeDescription: {text: "A shortcut node that takes you to a special mode."},
    guestbookTitle: {text: "📝 Leave a message for the developer (Hyeonjun Lee)"},
    guestNicknameLabel: {html: "Nickname: <b id='guestUsername'></b>"},
    guestMessage: {placeholder: "Message..."},
    guestSubmitBtn: {text: "Submit"},
    coffeeBtn: {text: "☕ Buy the developer (Hyeonjun Lee) a coffee"},
    shareTitle: {text: "🔗 Shareable content"},
    copyShareBtn: {text: "Copy"},
    closeShareBtn: {text: "Close"},
    settingsTitle: {text: "🛠️ Settings"},
    themeHeading: {text: "🎨 Themes"},
    themePreviewLabel: {text: "Preview"},
    autoSaveLabel: {text: "Auto-save circuit"},
    bgmLabel: {text: "BGM"},
    sfxLabel: {text: "SFX"},
    settingsCloseBtn: {text: "Close"},
    backToMainFromProblem: {text: "← Back to Main"},
    problemCreatorTitle: {text: "📝 Problem Creator"},
    gridSizeControllerLabel: {text: "🧭 Grid Size"},
    addRowTopBtn: {text: "↑", title: "Add top row", ariaLabel: "Add top row"},
    removeRowTopBtn: {text: "↓", title: "Remove top row", ariaLabel: "Remove top row"},
    addRowBottomBtn: {text: "↓", title: "Add bottom row", ariaLabel: "Add bottom row"},
    removeRowBottomBtn: {text: "↑", title: "Remove bottom row", ariaLabel: "Remove bottom row"},
    addColLeftBtn: {text: "←", title: "Add left column", ariaLabel: "Add left column"},
    removeColLeftBtn: {text: "→", title: "Remove left column", ariaLabel: "Remove left column"},
    addColRightBtn: {text: "→", title: "Add right column", ariaLabel: "Add right column"},
    removeColRightBtn: {text: "←", title: "Remove right column", ariaLabel: "Remove right column"},
    inputLabel: {text: "Inputs"},
    outputLabel: {text: "Outputs"},
    rowLabel: {text: "Rows"},
    colLabel: {text: "Cols"},
    problemWireMoveInfo: {title: "Default mode", ariaLabel: "Default mode"},
    problemWireStatusInfo: {title: "Ctrl / Cmd - Draw wire", ariaLabel: "Ctrl or Cmd - Draw wire"},
    problemWireDeleteInfo: {title: "Shift - Delete wire/block", ariaLabel: "Shift - Delete wire or block"},
    problemWireSelectInfo: {title: "Right click - Select", ariaLabel: "Right click - Select"},
    problemDeleteAllInfo: {title: "R - Reset circuit", ariaLabel: "R - Reset circuit"},
    saveProblemBtn: {text: "Save Problem"},
    problemInfoTitle: {text: "Enter Problem Info"},
    problemTitleInput: {placeholder: "Problem title"},
    problemDescInput: {placeholder: "Problem description"},
    problemDifficultyLabel: {text: "Difficulty"},
    problemDifficultyValue: {text: "{value}/5"},
    problemDifficultyStarAria: {text: "Difficulty {value} out of 5"},
    problemGridSizeLabel: {text: "Grid size"},
    fixIOCheckLabel: {text: "Fix IN/OUT positions"},
    confirmSaveProblemBtn: {text: "Save"},
    cancelSaveProblemBtn: {text: "Cancel"},
    problemSaveNeedsIO: {text: "Place at least one IN and one OUT block."},
    problemSaveNeedsSequentialIO: {text: "Number IN and OUT blocks sequentially starting from 1."},
    problemSaveFixErrors: {text: "Fix circuit errors before saving."},
    backToMainBtn: {text: "← Back to Main"},
    backToStageMapFromUserProblems: {text: "← Back to Stage Map"},
    userProblemsTitle: {text: "📝 User Problems"},
    openProblemCreatorBtn: {text: "Create Problem"},
    userProblemSearchLabel: {text: "Search"},
    userProblemSearch: {placeholder: "Title or from:creator"},
    userProblemSortLabel: {text: "Sort"},
    userProblemSortLatestOption: {text: "Latest"},
    userProblemSortPopularOption: {text: "Popular"},
    userProblemSortSolvedOption: {text: "Most solved"},
    userProblemSortDifficultyOption: {text: "Difficulty"},
    userProblemSortNameOption: {text: "Name"},
    userProblemSearchHelp: {text: "e.g. XOR, from:garden"},
    userProblemFilterMine: {text: "My Problems"},
    userProblemFilterUnsolved: {text: "Unsolved"},
    userProblemFilterPopular: {text: "Popular"},
    userProblemAdvancedSummary: {text: "⚙ Filters"},
    userProblemFilterGridLabel: {text: "Grid size"},
    userProblemFilterGridAnyOption: {text: "All"},
    userProblemFilterDifficultyLabel: {text: "Difficulty"},
    userProblemFilterDifficultyAll: {text: "All"},
    userProblemFilterDifficultyEasy: {text: "Easy"},
    userProblemFilterDifficultyNormal: {text: "Normal"},
    userProblemFilterDifficultyHard: {text: "Hard"},
    userProblemFilterMinLikesLabel: {text: "Likes at least"},
    userProblemMinLikes: {placeholder: "0"},
    userProblemFilterCreatorLabel: {text: "Creator"},
    userProblemCreatorFilter: {placeholder: "e.g. garden"},
    userProblemResetFilters: {text: "Reset filters"},
    userProblemResultSummaryTemplate: {text: "Showing {visible} of {total} problems"},
    userProblemNoMatch: {text: "No problems match the selected filters."},
    problemUntitled: {text: "Untitled problem"},
    userProblemLoadFailed: {text: "Failed to load user problems."},
    rankingTitle: {text: "🏆 Ranking"},
    hintTitle: {text: "💡 Hint"},
    hintLabel: {text: "Hint"},
    hintReady: {text: "You can view the next hint now."},
    hintCountdown: {text: "Time until next hint {time}"},
    noHints: {text: "No hints available."},
    startStageFirst: {text: "Start a stage first."},
    adHintBtn: {text: "Watch ad to get hint"},
    closeHintBtn: {text: "Close"},
    closeHintMessageBtn: {text: "Close"},
    gradeButton: {text: "Grade"},
    wireMoveInfo: {title: "Default mode", ariaLabel: "Default mode"},
    wireStatusInfo: {title: "Ctrl / Cmd - Draw wire", ariaLabel: "Ctrl or Cmd - Draw wire"},
    wireDeleteInfo: {title: "Shift - Delete wire/block", ariaLabel: "Shift - Delete wire or block"},
    wireSelectInfo: {title: "Right click - Select", ariaLabel: "Right click - Select"},
    DeleteAllInfo: {title: "R - Reset circuit", ariaLabel: "R - Reset circuit"},
    usedBlocksLabel: {text: "Blocks"},
    usedWiresLabel: {text: "Wires"},
    problemUsedBlocksLabel: {text: "Blocks"},
    problemUsedWiresLabel: {text: "Wires"},
    returnToEditBtn: {text: "🛠 Back to Edit"},
    saveCircuitBtn: {text: "💾 Save Circuit"},
    viewSavedBtn: {text: "💾 View Saved Circuits"},
    viewRankingBtn: {text: "🏆 View Ranking"},
    showIntroBtn: {text: "ℹ️ Stage Info"},
    hintBtn: {text: "💡 Hint"},
    backToLevelsBtn: {text: "← Back to Level Select"},
    tutPrevBtn: {text: "Prev"},
    tutNextBtn: {text: "Next"},
    tutFinishBtn: {text: "Finish Tutorial"},
    tutCloseBtn: {text: "Close"},
    savedListTitle: {text: "💾 Saved Circuits"},
    closeSavedModal: {text: "Close"},
    gifLoadingText: {text: "Generating GIF..."},
    saveGifBtn: {text: "Save Image"},
    copyGifBtn: {text: "Copy Image"},
    shareGifBtn: {text: "Share"},
    closeGifModal: {text: "Close"},
    savingCircuit: {text: "Saving circuit..."},
    circuitSaved: {text: "Circuit saved!"},
    loginToSaveCircuit: {text: "Log in with Google to save the circuit."},
    savedShareBtn: {text: "Share"},
    savedNextBtn: {text: "Next"},
    problemListTitle: {text: "📂 Saved Problems"},
    closeProblemListModal: {text: "Close"},
    clearedTitle: {html: "<span id='clearedStageName'></span> Cleared!"},
    startLevelBtn: {text: "Start"},
    clearedNextBtn: {text: "Next"},
    loadBtn: {text: "Load"},
    deleteBtn: {text: "Delete"},
    logoutBtn: {text: "Logout"},
    outputMissingAlert: {text: "❌ Missing output blocks: {list}"},
    loginFailed: {text: "Login failed. Code: {code}, Message: {message}"},
    noCircuits: {text: "No saved circuits."},
    noProblems: {text: "No saved problems."},
    noUserProblems: {text: "No problems available."},
    confirmDelete: {text: "Are you sure you want to delete?"},
    loadFailedNoData: {text: "Load failed: No data"},
    incompatibleCircuit: {text: "This circuit is incompatible with the current version."},
    loadFailed: {text: "Load failed"},
    loginRequired: {text: "Login required."},
    googleLoginPrompt: {text: "Please log in with Google."},
    deleteFailed: {text: "Delete failed: {error}"},
    confirmDeleteAll: {text: "⚠️ Delete all blocks and wires?"},
    problemTitleRequired: {text: "Please enter a problem title."},
    problemDescRequired: {text: "Please enter a problem description."},
    problemSaved: {text: "Problem saved."},
    saveFailed: {text: "Save failed: {error}"},
    thInput: {text: "Input"},
    thExpected: {text: "Expected"},
    thActual: {text: "Actual"},
    thResult: {text: "Result"},
    thRank: {text: "Rank"},
    thNickname: {text: "Nickname"},
    thStage: {text: "Stage"},
    thBlocks: {text: "Blocks"},
    thWires: {text: "Wires"},
    thHintUsed: {text: "Hints"},
    thTime: {text: "Time"},
    thTitle: {text: "Title"},
    thGrid: {text: "Grid"},
    thNotes: {text: "Notes"},
    thCreator: {text: "Creator"},
    thCreatedAt: {text: "Created"},
    thSolved: {text: "Solved"},
    thLikes: {text: "Likes"},
    orientationWarningText: {text: "⚠️ Bitwiser works best in landscape."},
    orientationTipText: {text: "Tip: Install Bitwiser via [Add to Home Screen → Install]!"},
    closeOrientationBtn: {text: "Close"},
    mainTagline: {text: "Play bitwise. Become bit wiser."},
    mobileNavRankingText: {text: "Ranking"},
    mobileNavRankingIcon: {alt: "Ranking"},
    mobileNavHomeText: {text: "Home"},
    mobileNavHomeIcon: {alt: "Home"},
    mobileNavGuestbookText: {text: "Guestbook"},
    mobileNavGuestbookIcon: {alt: "Guestbook"},
    labExitBtn: {text: "⟲ Back to Main", ariaLabel: "Return to main screen"},
    communityShareClose: {ariaLabel: "Close"},
    communityShareTitleLabel: {text: "Share to Circuit Community"},
    communityShareIntro: {text: "Share your current lab circuit with the community."},
    communityShareTitleFieldLabel: {text: "Circuit title"},
    communityShareTitle: {placeholder: "e.g. 4-bit parity generator"},
    communityShareDescriptionLabel: {text: "Description (optional)"},
    communityShareDescription: {placeholder: "Briefly describe how your circuit works or tips."},
    communityShareCancel: {text: "Cancel"},
    communityShareSubmit: {text: "Share"},
    communityBrowserTitle: {text: "Circuit Community"},
    communityBrowserClose: {ariaLabel: "Close"},
    communityLoading: {text: "Loading circuit list..."},
    communityEmptyState: {text: "No circuits have been shared yet."},
    labCommunityTitle: {text: "🌐 Circuit Community"},
    labShareCommunityBtn: {text: "Share to community"},
    labOpenCommunityBtn: {text: "Browse community"},
    labCommunityLoginHint: {text: "Sign in with Google to use this feature."},
    userProblemsSubtitle: {text: "Search and sort community-made puzzles."},
    userProblemFallbackTitle: {text: "User Problem"},
    circuitError: {text: "The circuit has errors."},
    featureComingSoon: {text: "This feature is coming soon."},
    communityUnknownUser: {text: "Unknown user"},
    anonymousUser: {text: "Anonymous"},
    communityLoginRequired: {text: "Please sign in with Google to continue."},
    communityFirestoreUnavailable: {text: "Please check the Firestore connection."},
    communityStatsUnavailable: {text: "Unable to load circuit stats."},
    communityStatsTemplate: {text: "Blocks {blocks} · Wires {wires}"},
    communityFirestoreInitFailed: {text: "Failed to initialize Firestore."},
    communityCircuitNotFound: {text: "Circuit not found."},
    communityUploadInProgress: {text: "Uploading circuit..."},
    communityUntitledCircuit: {text: "Untitled circuit"},
    communityShareSuccess: {text: "Shared to the community!"},
    communityShareSuccessStatus: {text: "Your circuit has been uploaded to the community."},
    communityUploadFailed: {text: "Upload failed. Please try again later."},
    communityCardMetaTemplate: {text: "{author} • {date}"},
    communityCardStatsTemplate: {text: "Blocks {blocks} · Wires {wires}"},
    communityLoadButton: {text: "Load this circuit"},
    communityLoadCircuitFailed: {text: "Failed to load circuit data."},
    communityApplyCircuitFailed: {text: "Failed to apply the circuit."},
    communityLoadCircuitSuccess: {text: "Loaded the community circuit."},
    communityDeleteButton: {text: "Delete my circuit"},
    communityDeleteConfirm: {text: "Delete this circuit? This cannot be undone."},
    communityDeleting: {text: "Deleting..."},
    communityDeleteSuccess: {text: "Circuit deleted."},
    communityDeleteSuccessStatus: {text: "Removed the community circuit."},
    communityDeleteSuccessEmpty: {text: "Circuit deleted. No circuits remain."},
    communityDeleteFailed: {text: "Failed to delete circuit. Please try again later."},
    communityListLoading: {text: "Loading circuit list..."},
    communityListEmpty: {text: "No circuits yet. Be the first to share!"},
    communityListLoaded: {text: "Loaded {count} circuits."},
    communityListLoadFailed: {text: "Failed to load circuit list."},
    communityStatusLoginRequired: {text: "Please sign in with Google to continue."},
    guestbookMessageRequired: {text: "Please enter a message."},
    guestbookSubmitFailed: {text: "Failed to submit."},
    circuitErrorAlert: {text: "The circuit has errors."},
    gifCopySuccess: {text: "Image copied to clipboard."},
    gifCopyFailed: {text: "Failed to copy image."},
    gifShareNotSupported: {text: "Sharing is not supported in this browser."},
    saveCircuitError: {text: "An error occurred while saving the circuit."},
    statusShareIntro: {text: "I played Bitwiser!"},
    statusShareCopySuccess: {text: "Copied to clipboard!"},
    statusShareCopyFailed: {text: "Failed to copy: {error}"},
    statusShareNoSavedCircuit: {text: "No recently saved circuit."},
    statusShareNoGif: {text: "No GIF available to share."},
    statusShareNotSupported: {text: "Sharing is not supported."},
    statusShareFailed: {text: "Share failed: {error}"},
    gradingMultipleInputs: {text: "❌ Multiple inputs are connected to the {blockType} block. Please fix the circuit."},
    gradingResultsHeading: {html: "<b>Results:</b><br><br>"},
    gradingCorrect: {text: "✅ Correct"},
    gradingIncorrect: {text: "❌ Incorrect"},
    gradingAllPassed: {text: "🎉 All tests passed!"},
    gradingSomeFailed: {text: "😢 Some tests failed."},
    rankingLoading: {text: "Loading…"},
    noRanking: {text: "No ranking data."},
    refreshRankingBtn: {text: "🔄 Refresh"},
    closeRankingBtn: {text: "Close"},
    rankingLoadFailed: {text: "Failed to load rankings."},
    rankingSelectLevelFirst: {text: "Please select a level first."},
    loginNicknameRequired: {text: "Please enter a nickname."},
    loginNicknameTaken: {text: "This nickname is already taken."},
    loginNicknameRegisterError: {text: "An error occurred while registering the nickname."},
    loginRegisterButton: {text: "Register nickname"},
    loginModalTitleGoogle: {text: "Register Google nickname"},
    loginNicknameExists: {text: "Nickname already exists."},
    loginMergePromptTitle: {html: "<p>Progress for nickname <b>{targetName}</b></p>"},
    loginMergePromptSummary: {html: "<li>Levels cleared: {cleared}</li><li>Blocks used: {blocks}</li><li>Wires used: {wires}</li>"},
    loginMergePromptQuestion: {text: "Merge this progress with your account?"},
    loginConfirm: {text: "Yes"},
    loginCancel: {text: "Not my account"},
    authUnknownError: {text: "An unknown error occurred."},
    usernameRegistering: {text: "Register nickname"},
    rankOverall: {text: "All"}
  }
};

let currentLang = localStorage.getItem('lang') || (navigator.language && navigator.language.startsWith('ko') ? 'ko' : 'en');

function applyTranslations() {
  const langMap = translations[currentLang];
  Object.keys(langMap).forEach(id => {
    const el = document.getElementById(id);
    if (!el) return;
    const {text, html, placeholder, title, ariaLabel, alt} = langMap[id];
    if (text !== undefined) el.textContent = text;
    if (html !== undefined) el.innerHTML = html;
    if (placeholder !== undefined) el.setAttribute('placeholder', placeholder);
    if (title !== undefined) el.setAttribute('title', title);
    if (ariaLabel !== undefined) el.setAttribute('aria-label', ariaLabel);
    if (alt !== undefined) el.setAttribute('alt', alt);
  });
}

function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('lang', lang);
  location.reload();
}

document.addEventListener('DOMContentLoaded', () => {
  applyTranslations();
  const langBtn = document.getElementById('languageBtn');
  if (langBtn) {
    langBtn.addEventListener('click', () => {
      setLanguage(currentLang === 'ko' ? 'en' : 'ko');
    });
  }
});

window.currentLang = currentLang;
window.t = function(id) {
  const entry = translations[currentLang][id] || translations['en'][id];
  return entry && (entry.text || entry.html) || id;
};
window.setLanguage = setLanguage;
